# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fb260380af7ff2351c9c9f3aad8620042c13903fe412cb7004f47cc42e185ccf420310f5e8441231a5378b13c643639007ebb8cab89ae596bdf1c321ba7d666

test:
  secret_key_base: d6e57dbf440c2b0fb9cb0bd546768782f0d7ff076a1ece629f610f0b3102471887b5a9209c864bd323bc31610f89ccae51ffa0b2d5da23c0769f7e050fbd21cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
